Add AlphaWallet connector
blocknative/onboard pull request #505
Opened 2021-03-04 23:30 UTC by JamesSmartCell

Adding AlphaWallet as an option for onboard interface.

2021-03-23 23:50 UTC, taylorjdawson commented
@JamesSmartCell thanks for this! Taking a look 👀

2021-03-23 23:54 UTC, taylorjdawson requested changes

2021-03-23 23:54 UTC, taylorjdawson commented on src/modules/select/wallets/alphawallet.ts
> +      if isAlphaWallet && rpcUrl) {
@JamesSmartCell Should there be an opening parenthesis here? 
```suggestion
      if (isAlphaWallet && rpcUrl) {
```

2021-04-05 19:14 UTC, taylorjdawson requested changes
Please run the following command to format your code according to the formatting guidelines
```
npx prettier --write src/modules/select/wallets/ownbit.ts
```

2021-04-05 19:14 UTC, taylorjdawson commented on src/modules/select/wallet-icons/icon-alphawallet.ts
> +export default alphawalletIcon
@JamesSmartCell Add new line here

2021-04-05 19:15 UTC, taylorjdawson commented
@JamesSmartCell Also if you could update this branch with develop, thanks!

2021-04-06 00:23 UTC, JamesSmartCell commented
Hi @taylorjdawson thanks for checking our PR :) I merged and applied formatting as directed, can you re-check? Thanks.

2021-04-09 00:29 UTC, taylorjdawson commented
Looks good! 👍

2021-04-09 00:30 UTC, taylorjdawson approved these changes

2021-04-09 00:30 UTC, merged