add tp wallet
blocknative/onboard pull request #576
Opened 2021-06-07 08:51 UTC by yudetamago

Hi, I'd like to add tokenpocket (named `tp`)  wallet.
How to check if it works?

I found [react-demo](https://github.com/blocknative/react-demo) repo and added `tp` to it ( https://github.com/blocknative/react-demo/pull/66/files ) but the wallet is not displayed...

Our website is https://tokenpocket.jp/en/

Thanks!

2021-06-07 18:46 UTC, taylorjdawson commented
@yudetamago Thanks for the PR! Will take a look 👀

2021-06-07 18:47 UTC, taylorjdawson requested changes

2021-06-07 18:47 UTC, taylorjdawson commented on src/utilities.ts
> +  if (provider.IsTp) {
@yudetamago I believe this may be your issue for the wallet not displaying in the react-demo? I think it should be lowercase: `isTp`

2021-07-07 17:05 UTC, taylorjdawson commented
@yudetamago When you get that change can you fix and sync with uptream branch then we can get it merged, thanks!

2021-07-26 07:44 UTC, yudetamago commented
@taylorjdawson 
Sorry for late reply, I fixed it.
Could you review this?

2021-07-28 22:51 UTC, taylorjdawson approved these changes

2021-07-28 22:51 UTC, merged