Add MyEtherWallet's MEW Wallet to Onboard
blocknative/onboard pull request #666
Opened 2021-08-20 00:57 UTC by gamalielhere

### Description

Add MyEtherWallet's MEW Wallet to Onboard

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [x] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works
- [ ] This PR passes the Circle CI checks

2021-09-01 22:00 UTC, taylorjdawson commented
@gamalielhere Looks like I am unable to make changes to this branch. Could you grant write permissions or merge latest develop into this branch? Thanks!

2021-09-01 23:02 UTC, gamalielhere commented
@taylorjdawson just pushed! let me know if you guys need anything else

2021-09-02 17:22 UTC, taylorjdawson requested changes
Small change and then it should be good! @gamalielhere

2021-09-02 17:22 UTC, taylorjdawson commented on src/interfaces.ts
> +  networkId: number
@gamalielhere `networkId` is already a part of `CommonWalletOptions` so we should remove it from here

2021-09-02 18:49 UTC, gamalielhere commented
@taylorjdawson just pushed the fixes!

2021-09-02 18:52 UTC, taylorjdawson approved these changes

2021-09-02 18:53 UTC, merged