chore: change xdefi redirect link to chrome store
blocknative/onboard pull request #833
Opened 2022-02-17 12:31 UTC by loxator

### Description
chore: change xdefi redirect link to chrome store

### Checklist
- [x] The version field in `package.json` is incremented following [semantic versioning](https://semver.org/)
- [ ] The box that allows repo maintainers to update this PR is checked
- [x] I tested locally to make sure this feature/fix works
- [x] This PR passes the Circle CI checks (if **merging a fork** run `yarn` with node version 12.22.7 to ensure no errors)

2022-02-23 20:00 UTC, Adamj1232 requested changes
Thanks for this PR! Just a couple small changes

2022-02-23 20:00 UTC, Adamj1232 commented on .gitignore
> +.history/
Can you please add an empty line at the bottom of this file if you have a moment?

2022-02-24 08:15 UTC, loxator commented on package.json
> +  "version": "1.38.2",
@Adamj1232 , thanks for pointing it out. I have addressed your comments :smile: .

2022-02-24 16:23 UTC, Adamj1232 approved these changes
Thank you!!

2022-02-24 16:38 UTC, merged